general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'SAP Academy for Engineering_team5'
      space: 'Dev'
      credentialsId: 'CF_CREDENTIALSID'